# Configures static analysis for Dart code.
# Lint results appear in Dart IDEs and via `flutter analyze`.

# Use Flutter's recommended lint set
include: package:flutter_lints/flutter.yaml

linter:
  # Lint rules: https://dart.dev/lints
  rules:
    always_use_package_imports: true  # 絶対パスでのimportを強制する
    prefer_final_locals: true  # ローカル変数はfinalを使用する
    prefer_const_constructors: true  # コンストラクタはconstを使用する
    prefer_const_literals_to_create_immutables: true  # リテラルはconstを使用する

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
